services:
  auth:
    build:
      dockerfile: Dockerfile
      context: ./AuthentificationService
    ports:
      - 8080:8084
    networks:
      blog_network:
        ipv4_address: 10.5.0.6
    links:
      - db
    depends_on:
      - db

  celestial:
    build:
      dockerfile: Dockerfile
      context: ./ObservationService
    ports:
      - 8080:8083
    networks:
      blog_network:
        ipv4_address: 10.5.0.5
    links:
      - db
    depends_on:
      - db

  observation:
    build:
      dockerfile: Dockerfile
      context: ./UtilisateurService
    ports:
      - 8080:8082
    networks:
      blog_network:
        ipv4_address: 10.5.0.4
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      #MYSQL_DATABASE: spring_blog_dto
    volumes:
      - data:/var/lib/ecf4
    ports:
      - 3307:3306
    networks:
      blog_network:
        ipv4_address: 10.5.0.3
volumes:
  data:

networks:
  blog_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16